In [2]:
# For colab
!pip install pytest pylint ipdb jupyterlab numpy pandas matplotlib seaborn scikit-learn tensorflow timm transformers keras_hub

In [3]:
import pandas as pd
import numpy as np
from tensorflow.keras.utils import image_dataset_from_directory

In [4]:
image_data_dir = "data/image_dataset"
image_dataset = image_dataset_from_directory(image_data_dir,
                                            labels="inferred",
                                            label_mode="binary",
                                            )
image_dataset


NotFoundError: Could not find directory data/image_dataset

In [ ]:
image_dataset

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>

In [ ]:
for sample in image_dataset.take(1):
    print(sample)

(<tf.Tensor: shape=(32, 256, 256, 3), dtype=float32, numpy=
array([[[[ 78.98242  ,  78.98242  ,  52.98242  ],
         [ 76.28125  ,  76.19336  ,  50.26367  ],
         [ 91.47266  ,  86.44336  ,  64.44336  ],
         ...,
         [ 84.37695  ,  77.14258  ,  59.054688 ],
         [ 72.19336  ,  69.12305  ,  54.070312 ],
         [ 65.041016 ,  62.041016 ,  47.041016 ]],

        [[ 66.30774  ,  65.0343   ,  39.67102  ],
         [ 73.74557  ,  72.406624 ,  47.102463 ],
         [ 89.67442  ,  84.64513  ,  62.645126 ],
         ...,
         [ 95.8752   ,  88.62217  ,  70.49697  ],
         [ 89.284035 ,  86.21372  ,  71.16099  ],
         [ 85.39736  ,  82.39736  ,  67.39736  ]],

        [[ 59.869858 ,  57.07617  ,  32.078484 ],
         [ 73.75212  ,  70.1282   ,  45.575462 ],
         [ 83.30994  ,  77.07393  ,  55.48002  ],
         ...,
         [117.30213  , 109.2494   ,  91.497444 ],
         [109.383125 , 106.29894  ,  91.25314  ],
         [102.95512  ,  99.95512  ,  84.9551

2026-03-09 17:27:57.846408: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
table_df_primary = pd.read_csv("data/table_dataset/primary_data.csv", delimiter=";")
table_df_secondary = pd.read_csv("data/table_dataset/secondary_data.csv", delimiter=";")

table_df_primary

,family,name,class,cap-diameter,cap-shape,Cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,Spore-print-color,habitat,season
0,Amanita Family,Fly Agaric,p,"[10, 20]","[x, f]","[g, h]","[e, o]",[f],[e],NaN,[w],"[15, 20]","[15, 20]",[s],[y],[w],[u],[w],[t],"[g, p]",NaN,[d],"[u, a, w]"
1,Amanita Family,Panther Cap,p,"[5, 10]","[p, x]",[g],[n],[f],[e],NaN,[w],"[6, 10]","[10, 20]",NaN,[y],[w],[u],[w],[t],[p],NaN,[d],"[u, a]"
2,Amanita Family,False Panther Cap,p,"[10, 15]","[x, f]",NaN,"[g, n]",[f],[e],NaN,[w],"[10, 12]","[10, 20]",NaN,NaN,[w],[u],[w],[t],"[e, g]",NaN,[d],"[u, a]"
3,Amanita Family,The Blusher,e,"[5, 15]","[x, f]",NaN,[n],[t],NaN,NaN,[w],"[7, 15]","[10, 25]",[b],NaN,[w],[u],[w],[t],[g],NaN,[d],"[u, a]"
4,Amanita Family,Death Cap,p,"[5, 12]","[x, f]",[h],[r],[f],NaN,[c],[w],"[10, 12]","[10, 20]",NaN,NaN,[w],[u],[w],[t],"[g, p]",NaN,[d],"[u, a]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,Saddle-Cup Family,White Saddle,p,"[2, 6]",[o],NaN,[w],[f],[f],[f],[f],"[4, 7]","[20, 40]",NaN,[g],[w],NaN,NaN,[t],[f],NaN,"[p, d]","[u, a]"
169,Bracket Fungi,Elfin's Saddle,p,"[2, 4]",[o],NaN,"[g, k]",[f],[f],[f],[f],"[2, 5]","[10, 20]",NaN,[g],"[g, n]",NaN,NaN,[f],[f],NaN,[d],"[u, a]"
170,Bracket Fungi,Turban Fungus,p,"[5, 15]",[o],NaN,"[n, e]",[f],[f],[f],[f],"[2, 5]","[20, 30]",NaN,[g],[n],NaN,NaN,[f],[f],NaN,[d],"[s, u]"
171,Morel Family,Common Morel,e,"[3, 8]","[p, c, o]",NaN,"[n, g]",[f],[f],[f],[f],"[3, 8]","[15, 25]",NaN,NaN,[n],NaN,NaN,[f],[f],NaN,"[l, d]",[s]


In [ ]:
table_df_secondary

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,spore-print-color,habitat,season
0,p,15.26,x,g,o,f,e,NaN,w,16.95,17.09,s,y,w,u,w,t,g,NaN,d,w
1,p,16.60,x,g,o,f,e,NaN,w,17.99,18.19,s,y,w,u,w,t,g,NaN,d,u
2,p,14.07,x,g,o,f,e,NaN,w,17.80,17.74,s,y,w,u,w,t,g,NaN,d,w
3,p,14.17,f,h,e,f,e,NaN,w,15.77,15.98,s,y,w,u,w,t,p,NaN,d,w
4,p,14.64,x,h,o,f,e,NaN,w,16.53,17.20,s,y,w,u,w,t,p,NaN,d,w
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61064,p,1.18,s,s,y,f,f,f,f,3.93,6.22,NaN,NaN,y,NaN,NaN,f,f,NaN,d,a
61065,p,1.27,f,s,y,f,f,f,f,3.18,5.43,NaN,NaN,y,NaN,NaN,f,f,NaN,d,a
61066,p,1.27,s,s,y,f,f,f,f,3.86,6.37,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u
61067,p,1.24,f,s,y,f,f,f,f,3.56,5.44,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u


# Pretrained model

In [ ]:
import timm
import torch
import torchvision.transforms as T
from PIL import Image
from urllib.request import urlopen

/home/clement/.pyenv/versions/kinoko/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
model = timm.create_model("hf-hub:BVRA/beit_base_patch16_224.in1k_ft_fungitastic_224", pretrained=True)
model = model.eval()

train_transforms = T.Compose([T.Resize((224, 224)), 
                              T.ToTensor(), 
                              T.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])]) 

img = Image.open("data/image_dataset/poisonous/Russula_emetica/Russula_emetica25.png")

output = model(train_transforms(img).unsqueeze(0))
output

tensor([[-3.8606, -0.9374,  2.6200,  ...,  0.8103, -2.3272,  2.0275]],
       grad_fn=<AddmmBackward0>)

In [ ]:
import torch.nn.functional as F
# Get probabilities
probs = F.softmax(output, dim=1)
top5 = probs.topk(5)

# Get class labels from the model config
print(model.pretrained_cfg)  # check if label map is embedded

# Or access directly:
label_map = model.pretrained_cfg.get('label_map') or model.pretrained_cfg.get('classes')

# Top predictions
for prob, idx in zip(top5.values[0], top5.indices[0]):
    label = label_map[idx.item()] if label_map else idx.item()
    print(f"{label}: {prob.item():.4f}")

{'hf_hub_id': 'BVRA/beit_base_patch16_224.in1k_ft_fungitastic_224', 'source': 'hf-hub', 'architecture': 'beit_base_patch16_224', 'custom_load': False, 'input_size': [3, 224, 224], 'fixed_input_size': False, 'interpolation': 'bicubic', 'crop_pct': 0.875, 'crop_mode': 'center', 'mean': (0.485, 0.456, 0.406), 'std': (0.229, 0.224, 0.225), 'num_classes': 2829, 'pool_size': None, 'first_conv': None, 'classifier': None}
2364: 0.9981
2346: 0.0017
2393: 0.0001
2382: 0.0000
2397: 0.0000


In [ ]:
df_test = pd.read_csv("~/Downloads/FungiTastic-OpenSet-Test.csv")

In [ ]:
df_test[df_test.category_id == 2364].head(1)

,eventDate,year,month,day,habitat,countryCode,scientificName,kingdom,phylum,class,order,family,genus,specificEpithet,hasCoordinate,species,iucnRedListCategory,substrate,latitude,longitude,coorUncert,observationID,region,district,filename,category_id,metaSubstrate,poisonous,captions
15245,2023-09-16,2023.0,9.0,16.0,heath,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.067781,9.204794,15.0,4465878906,Midtjylland,Ikast-Brande,0-4465878906.JPG,2364,jord,1,The image shows a single mushroom as the centr...


## Fine tuning

In [ ]:
import os
os.environ["KERAS_BACKEND"] = "tensorflow"

import keras
import keras_hub
import tensorflow as tf
import numpy as np

In [ ]:
# --- CONFIGURATION ---
# DINOv2 Base preset expects 518x518
IMG_SIZE = 518  
# NUM_CLASSES = 10 
BATCH_SIZE = 32
EPOCHS = 5
SEED = 42

In [ ]:
# --- 1. DATA PREPARATION ---

train_ds = tf.keras.utils.image_dataset_from_directory(
    image_data_dir,
    labels="inferred",
    label_mode="categorical", # Changed from 'binary' to match 10 classes
    validation_split=0.2,
    subset="training",
    seed=SEED,
    image_size=(IMG_SIZE, IMG_SIZE), # Changed to 518
    batch_size=BATCH_SIZE
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    image_data_dir,
    labels="inferred",
    label_mode="categorical", # Changed from 'binary'
    validation_split=0.2,
    subset="validation",
    seed=SEED,
    image_size=(IMG_SIZE, IMG_SIZE), # Changed to 518
    batch_size=BATCH_SIZE
)

Found 8076 files belonging to 2 classes.
Using 6461 files for training.
Found 8076 files belonging to 2 classes.
Using 1615 files for validation.


In [ ]:
# --- 2. MODEL BUILDING ---

backbone = keras_hub.models.DINOV2Backbone.from_preset("dinov2_base")

# Freeze the backbone
backbone.trainable = False

# Build the model
inputs = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))

# ImageNet Normalization
x = keras.layers.Rescaling(1/255.0)(inputs)
x = keras.layers.Normalization(
    mean=[0.485, 0.456, 0.406], 
    variance=[0.229**2, 0.224**2, 0.225**2]
)(x)

# Pass to backbone
outputs = backbone(x)[:, 0, :]

In [ ]:
# --- 3. CUSTOM HEAD ---
x = keras.layers.Dense(512, activation="relu")(outputs)
# x = keras.layers.BatchNormalization()(x)
# x = keras.layers.Dropout(0.3)(x)
# x = keras.layers.Dense(256, activation="relu")(x)
predictions = keras.layers.Dense(2, activation="softmax")(x)

model = keras.Model(inputs=inputs, outputs=predictions)

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss="categorical_crossentropy",
    metrics=["accuracy", "recall", "precision"]
)

model.summary()

Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_10 (InputLayer)     │ (None, 518, 518, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ rescaling_10 (Rescaling)        │ (None, 518, 518, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ normalization_10                │ (None, 518, 518, 3)    │             0 │
│ (Normalization)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dinov2_backbone                 │ (None, 1370, 768)      │    87,632,640 │
│ (DINOV2Backbone)                │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ get_item_3 (GetItem)            │ (None, 768)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 512)            │       393,728 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 2)              │         1,026 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 88,027,394 (335.80 MB)

 Trainable params: 394,754 (1.51 MB)

 Non-trainable params: 87,632,640 (334.29 MB)

In [ ]:
# --- 4. TRAINING ---
print("\nStarting training...")
model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS
)


Starting training...
Epoch 1/5


/home/clement/.pyenv/versions/kinoko/lib/python3.12/site-packages/keras/src/models/functional.py:241: UserWarning: The structure of `inputs` doesn't match the expected structure.
Expected: {'images': 'images'}
Received: inputs=Tensor(shape=(None, 518, 518, 3))
  warnings.warn(msg)
2026-03-10 09:32:02.995010: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 2882918400 exceeds 10% of free system memory.


In [ ]:
# # --- 5. OPTIONAL: FULL FINE-TUNING ---
# # After the head is trained, you can unfreeze and train with a tiny learning rate
# print("\nUnfreezing backbone for fine-tuning...")
# backbone.trainable = True
# model.compile(
#     optimizer=keras.optimizers.Adam(learning_rate=1e-6), # Extremely low LR
#     loss="categorical_crossentropy",
#     metrics=["accuracy"]
# )
# # model.fit(train_ds, validation_data=val_ds, epochs=2)

# # --- 6. EVALUATION & PREDICTION ---
# print("\nEvaluating model...")
# loss, accuracy = model.evaluate(val_ds)
# print(f"Validation Accuracy: {accuracy*100:.2f}%")

# # Prediction example
# sample_img = np.random.rand(1, IMG_SIZE, IMG_SIZE, 3).astype("float32")
# prediction = model.predict(sample_img)
# print(f"Prediction shape: {prediction.shape}")

In [ ]:
outputs

<KerasTensor shape=(None, 1370, 768), dtype=float32, sparse=False, ragged=False, name=keras_tensor_91>