In [17]:
import pandas as pd
import numpy as np
from tensorflow.keras.utils import image_dataset_from_directory

I0000 00:00:1773067442.239705 1477664 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [18]:
image_data_dir = "data/image_dataset"
image_dataset = image_dataset_from_directory(image_data_dir,
                                            labels="inferred",
                                            label_mode="binary",
                                            )
image_dataset


Found 8076 files belonging to 2 classes.


E0000 00:00:1773067448.073917 1477664 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>

In [19]:
image_dataset

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>

In [20]:
for sample in image_dataset.take(1):
    print(sample)

(<tf.Tensor: shape=(32, 256, 256, 3), dtype=float32, numpy=
array([[[[2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         ...,
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02]],

        [[2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         ...,
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02]],

        [[2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         ...,
         

In [21]:
df.head()

NameError: name 'df' is not defined

In [22]:
pd.set_option('display.max_columns', None)

In [23]:
table_df_primary = pd.read_csv("data/table_dataset/primary_data.csv", delimiter=";")
table_df_secondary = pd.read_csv("data/table_dataset/secondary_data.csv", delimiter=";")

table_df_primary

,family,name,class,cap-diameter,cap-shape,Cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,Spore-print-color,habitat,season
0,Amanita Family,Fly Agaric,p,"[10, 20]","[x, f]","[g, h]","[e, o]",[f],[e],NaN,[w],"[15, 20]","[15, 20]",[s],[y],[w],[u],[w],[t],"[g, p]",NaN,[d],"[u, a, w]"
1,Amanita Family,Panther Cap,p,"[5, 10]","[p, x]",[g],[n],[f],[e],NaN,[w],"[6, 10]","[10, 20]",NaN,[y],[w],[u],[w],[t],[p],NaN,[d],"[u, a]"
2,Amanita Family,False Panther Cap,p,"[10, 15]","[x, f]",NaN,"[g, n]",[f],[e],NaN,[w],"[10, 12]","[10, 20]",NaN,NaN,[w],[u],[w],[t],"[e, g]",NaN,[d],"[u, a]"
3,Amanita Family,The Blusher,e,"[5, 15]","[x, f]",NaN,[n],[t],NaN,NaN,[w],"[7, 15]","[10, 25]",[b],NaN,[w],[u],[w],[t],[g],NaN,[d],"[u, a]"
4,Amanita Family,Death Cap,p,"[5, 12]","[x, f]",[h],[r],[f],NaN,[c],[w],"[10, 12]","[10, 20]",NaN,NaN,[w],[u],[w],[t],"[g, p]",NaN,[d],"[u, a]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,Saddle-Cup Family,White Saddle,p,"[2, 6]",[o],NaN,[w],[f],[f],[f],[f],"[4, 7]","[20, 40]",NaN,[g],[w],NaN,NaN,[t],[f],NaN,"[p, d]","[u, a]"
169,Bracket Fungi,Elfin's Saddle,p,"[2, 4]",[o],NaN,"[g, k]",[f],[f],[f],[f],"[2, 5]","[10, 20]",NaN,[g],"[g, n]",NaN,NaN,[f],[f],NaN,[d],"[u, a]"
170,Bracket Fungi,Turban Fungus,p,"[5, 15]",[o],NaN,"[n, e]",[f],[f],[f],[f],"[2, 5]","[20, 30]",NaN,[g],[n],NaN,NaN,[f],[f],NaN,[d],"[s, u]"
171,Morel Family,Common Morel,e,"[3, 8]","[p, c, o]",NaN,"[n, g]",[f],[f],[f],[f],"[3, 8]","[15, 25]",NaN,NaN,[n],NaN,NaN,[f],[f],NaN,"[l, d]",[s]


In [24]:
table_df_secondary

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,spore-print-color,habitat,season
0,p,15.26,x,g,o,f,e,NaN,w,16.95,17.09,s,y,w,u,w,t,g,NaN,d,w
1,p,16.60,x,g,o,f,e,NaN,w,17.99,18.19,s,y,w,u,w,t,g,NaN,d,u
2,p,14.07,x,g,o,f,e,NaN,w,17.80,17.74,s,y,w,u,w,t,g,NaN,d,w
3,p,14.17,f,h,e,f,e,NaN,w,15.77,15.98,s,y,w,u,w,t,p,NaN,d,w
4,p,14.64,x,h,o,f,e,NaN,w,16.53,17.20,s,y,w,u,w,t,p,NaN,d,w
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61064,p,1.18,s,s,y,f,f,f,f,3.93,6.22,NaN,NaN,y,NaN,NaN,f,f,NaN,d,a
61065,p,1.27,f,s,y,f,f,f,f,3.18,5.43,NaN,NaN,y,NaN,NaN,f,f,NaN,d,a
61066,p,1.27,s,s,y,f,f,f,f,3.86,6.37,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u
61067,p,1.24,f,s,y,f,f,f,f,3.56,5.44,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u


# Pretrained model

In [25]:
import timm
import torch
import torchvision.transforms as T
from PIL import Image
from urllib.request import urlopen

In [42]:
model = timm.create_model("hf-hub:BVRA/beit_base_patch16_224.in1k_ft_fungitastic_224", pretrained=True)
model = model.eval()

train_transforms = T.Compose([T.Resize((224, 224)), 
                              T.ToTensor(), 
                              T.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])]) 

img = Image.open("data/image_dataset/poisonous/Russula_emetica/Russula_emetica25.png")

output = model(train_transforms(img).unsqueeze(0))
output

tensor([[-3.8606, -0.9374,  2.6200,  ...,  0.8103, -2.3272,  2.0275]],
       grad_fn=<AddmmBackward0>)

In [43]:
import torch.nn.functional as F
# Get probabilities
probs = F.softmax(output, dim=1)
top5 = probs.topk(5)

# Get class labels from the model config
print(model.pretrained_cfg)  # check if label map is embedded

# Or access directly:
label_map = model.pretrained_cfg.get('label_map') or model.pretrained_cfg.get('classes')

# Top predictions
for prob, idx in zip(top5.values[0], top5.indices[0]):
    label = label_map[idx.item()] if label_map else idx.item()
    print(f"{label}: {prob.item():.4f}")

{'hf_hub_id': 'BVRA/beit_base_patch16_224.in1k_ft_fungitastic_224', 'source': 'hf-hub', 'architecture': 'beit_base_patch16_224', 'custom_load': False, 'input_size': [3, 224, 224], 'fixed_input_size': False, 'interpolation': 'bicubic', 'crop_pct': 0.875, 'crop_mode': 'center', 'mean': (0.485, 0.456, 0.406), 'std': (0.229, 0.224, 0.225), 'num_classes': 2829, 'pool_size': None, 'first_conv': None, 'classifier': None}
2364: 0.9981
2346: 0.0017
2393: 0.0001
2382: 0.0000
2397: 0.0000


In [44]:
df_test = pd.read_csv("~/Downloads/FungiTastic-OpenSet-Test.csv")

In [46]:
df_test[df_test.category_id == 2364]

,eventDate,year,month,day,habitat,countryCode,scientificName,kingdom,phylum,class,order,family,genus,specificEpithet,hasCoordinate,species,iucnRedListCategory,substrate,latitude,longitude,coorUncert,observationID,region,district,filename,category_id,metaSubstrate,poisonous,captions
15245,2023-09-16,2023.0,9.0,16.0,heath,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.067781,9.204794,15.0,4465878906,Midtjylland,Ikast-Brande,0-4465878906.JPG,2364,jord,1,The image shows a single mushroom as the centr...
15246,2023-09-16,2023.0,9.0,16.0,heath,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.067781,9.204794,15.0,4465878906,Midtjylland,Ikast-Brande,1-4465878906.JPG,2364,jord,1,The image shows a single mushroom as the main ...
15247,2023-09-16,2023.0,9.0,16.0,heath,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.067781,9.204794,15.0,4465878906,Midtjylland,Ikast-Brande,2-4465878906.JPG,2364,jord,1,The image shows a single mushroom as the main ...
23327,2023-08-11,2023.0,8.0,11.0,Mixed woodland (with coniferous and deciduous ...,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,54.999977,15.063318,5.0,4465867600,Hovedstaden,Bornholm,0-4465867600.JPG,2364,jord,1,The image shows two distinct fungi with unique...
23328,2023-08-11,2023.0,8.0,11.0,Mixed woodland (with coniferous and deciduous ...,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,54.999977,15.063318,5.0,4465867600,Hovedstaden,Bornholm,1-4465867600.JPG,2364,jord,1,The image shows two distinctive fungi growing ...
24894,2023-09-11,2023.0,9.0,11.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.070778,9.210778,15.0,4465879814,Midtjylland,Ikast-Brande,0-4465879814.JPG,2364,jord,1,The image shows two distinctive mushrooms in a...
26565,2023-10-12,2023.0,10.0,12.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,55.077130,15.023643,15.0,4465890050,Hovedstaden,Bornholm,0-4465890050.JPG,2364,jord,1,"The image shows a single, prominent mushroom a..."
26566,2023-10-12,2023.0,10.0,12.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,55.077130,15.023643,15.0,4465890050,Hovedstaden,Bornholm,1-4465890050.JPG,2364,jord,1,The image showcases a striking mushroom as the...
26944,2023-10-18,2023.0,10.0,18.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,57.291803,11.003939,15.0,4465897407,Nordjylland,Læsø,0-4465897407.JPG,2364,jord,1,The image shows a striking red fungus with a d...
56405,2023-10-18,2023.0,10.0,18.0,Mixed woodland (with coniferous and deciduous ...,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,55.859750,8.238837,64.0,4465898340,NaN,NaN,0-4465898340.JPG,2364,jord,1,The image shows a striking mushroom lying on i...
